# Generated by Django 5.0.2 on 2024-02-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='characters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('used_cnt', models.IntegerField(default=0)),
                ('most_freq_char', models.ForeignKey(on_delete=models.SET(None), related_name='most_freq_char', to='app.characters')),
                ('most_freq_char2', models.ForeignKey(on_delete=models.SET(None), related_name='most_freq_char2', to='app.characters')),
                ('most_freq_char3', models.ForeignKey(on_delete=models.SET(None), related_name='most_freq_char3', to='app.characters')),
            ],
        ),
    ]
