# Generated by Django 5.0.2 on 2024-02-12 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.IntegerField(default=0)),
                ('wpm', models.IntegerField(default=0)),
                ('accuracyA', models.IntegerField(default=0)),
                ('accuracyB', models.IntegerField(default=0)),
                ('accuracyC', models.IntegerField(default=0)),
                ('accuracyD', models.IntegerField(default=0)),
                ('accuracyE', models.IntegerField(default=0)),
                ('accuracyF', models.IntegerField(default=0)),
                ('accuracyG', models.IntegerField(default=0)),
                ('accuracyH', models.IntegerField(default=0)),
                ('accuracyI', models.IntegerField(default=0)),
                ('accuracyJ', models.IntegerField(default=0)),
                ('accuracyK', models.IntegerField(default=0)),
                ('accuracyL', models.IntegerField(default=0)),
                ('accuracyM', models.IntegerField(default=0)),
                ('accuracyN', models.IntegerField(default=0)),
                ('accuracyO', models.IntegerField(default=0)),
                ('accuracyP', models.IntegerField(default=0)),
                ('accuracyQ', models.IntegerField(default=0)),
                ('accuracyR', models.IntegerField(default=0)),
                ('accuracyS', models.IntegerField(default=0)),
                ('accuracyT', models.IntegerField(default=0)),
                ('accuracyU', models.IntegerField(default=0)),
                ('accuracyV', models.IntegerField(default=0)),
                ('accuracyW', models.IntegerField(default=0)),
                ('accuracyX', models.IntegerField(default=0)),
                ('accuracyY', models.IntegerField(default=0)),
                ('accuracyZ', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
