# Generated by Django 5.0.2 on 2024-02-18 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_accuracy_alter_account_accuracya_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_accuracy',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='account',
            name='last_mistackes',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='account',
            name='last_wpm',
            field=models.IntegerField(default=1000),
        ),
    ]
