# Generated by Django 5.0.2 on 2024-02-18 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_last_accuracy_account_last_mistackes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='last_mistackes',
            new_name='last_mistakes',
        ),
    ]
